name: barter_app_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^5.13.0
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  ferry: ^0.14.2+1
  gql_http_link: ^1.1.0
  ferry_generator: ^0.8.1
  gql_build: ^0.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
